#@ load("@ytt:data", "data")

#@ def resource_image():
#@   return data.values.docker_registry + "/honeymarker-resource"
#@ end

jobs:
- name: build-image-image
  serial: true
  plan:
  - {get: repo, trigger: true}
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gcr.io/kaniko-project/executor
          tag: debug
      inputs:
      - name: repo
      outputs:
      - name: image
      run:
        path: /kaniko/executor
        args:
        - --context=repo
        - --use-new-run
        - --single-snapshot
        - --cache=false
        - --no-push
        - --tar-path=image/image.tar
  - put: edge-image
    params:
      image: image/image.tar

resources:
- name: repo
  type: git
  webhook_token: ((webhook.secret))
  source:
    ignore_paths: ["ci/*[^md]"]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch

- name: edge-image
  type: registry-image
  source:
    tag: edge
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ resource_image()
